### ISSUE TITLE
Still problems importing structural variants

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/gpsea#215]
```
cohort = load_phenopacket_folder(pp_directory=phenopacket_input_folder, cohort_creator=cohort_creator)
````
leads to errors for each patient with a structural variant, e.g., 
```
Patient PMID_20513137_individual_NF00663_GSM_GSM492680 has an error with variant SO:1000029_HGNC:7765_NF1. Try again or remove variant form testing
```
I am using the new cohort for NF1.

**Comment by ielis** [comment]
This issue may have been resolved in the meantime. I just loaded the *NF1* cohort from Phenopacket Store *0.1.19* and the cohort loaded with no issues.

Curiously, I did not find any individual with an ID that starts with `PMID_20513137`. So, there still may be something else going on. 

However, I will close this because the *NF1* cohort loads fine.
