### ISSUE TITLE
Weirdness with p value correction

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/gpsea#366]
The nominal and corrected p values for pulmonic stenosis are the same (PTPN11 cohort):
Let's double check the code for this -
![Screenshot 2024-11-30 at 14 01 16](https://github.com/user-attachments/assets/4706628d-3113-482b-944c-1c4dd05951c1)

**Comment by pnrobinson** [comment]
As a minor issue, it would be good to align all columns left!

**Comment by ielis** [comment]
I think this is OK, because the corrected p value is equal to the nominal p value only in the _last _ term. I think this is expected in Benjamini/Hochberg correction.

In other words, we test 3 terms and only in case of the 3rd term the corrected p value is equal to the nominal p value.

However, please let me know if this sounds weird..
